### ISSUE TITLE
Ordered lone Leaders not recognised by order counter

### ISSUE THREAD

**Issue by utl94** [riverwanderer/ccnapoleonics#239]
Module V5.1.0beta1
Vassal V3.7.13

When ordering units and Leaders after a card has been played, the counter on the left hand side of the board does not recognise and count lone Leaders as being ordered. Instead, the game implies that more orders than is legal may be dealt. Save and logfile included.

[LeaderCountBug.zip](https://github.com/user-attachments/files/16730582/LeaderCountBug.zip)

**Comment by riverwanderer** [comment]
Thanks for the report - I can confirm the bug. It has been fixed in beta2 release as part of #206  (I omitted to create an issue specifically for the fix). Current release on Vassal is beta3.

**Comment by riverwanderer** [comment]
Closing this issue. Any further issues or feedback always welcome. Thank you.
