### ISSUE TITLE
Issue/suggestion on Artillery Player Aid

### ISSUE THREAD

**Issue by utl94** [riverwanderer/ccnapoleonics#253]
Module V5.1.0beta5
Vassal V3.7.14
Scenario 001 Rolica (French First Position) - 17 August 1808

I do not really think this is an issue proper, rather a suggestion so please point me in the right direction if you wish such things as this to be reported elsewhere.

The Artillery Player Aid as displayed by the F1 key currently shows nothing in case of reduced fire power at 5 hex range (see image).

<img width="362" alt="ArtilleryPlayerAid" src="https://github.com/user-attachments/assets/ac18c767-d92a-40d5-b10f-7d710afeaf10">

I would prefer to see the 5 hex value be displayed as a dash (-). This would be consistent with both the "Ignore" column in the same Player Aid as well as keeping consistent with the printed Player Aids from GMT. Also it would clear any potential confusion for new players who may think that a value is missing (probably not but just for good measure). Either all dashes for missing values, or, perhaps since Player Aids are so wonderfully dynamic missing value columns should be omitted in their entirety for a more compact Player Aid?

**Comment by riverwanderer** [comment]
a803: Artillery player aids have variable length headings, eliminating empty or zero columns.
