### ISSUE TITLE
Wish for handling Mother Russia pre-roll Flag result

### ISSUE THREAD

**Issue by utl94** [riverwanderer/ccnapoleonics#255]
Module V5.1.0beta5
Vassal V3.7.14
Scenario 205 Eylau Plateau Russian Rearguard - 7 February 1807

[EDIT: below is my wish for how the counter could work more intuitively]
Mother Russia pre-roll Flag provides a lot of possibilities for the player (and presumably quite a lot of coding). However, currently when dragged and placed:
  * onto LT: automatically assumes Paper Strength block increase rather than giving the choice of constructing Fieldworks using the widget.
  * onto LN: automatically assumes Paper Strength block increase rather than giving the choice of constructing Fieldworks using the widget.
  * onto clear terrain: using the widget, will give the choice of deploying Cossacks or illegally constructing Fieldworks on empty hex.
  * onto FA: automatically assumes Paper Strength block increase rather than giving the choice of constructing Fieldworks using the widget.
  * onto (empty) Hill, Forest, Church, Frozen Lake: will provide the possibility to deploy Cossacks (as intended using the widget but this could happen automatically).

[MotherRussiaFlagBug.zip](https://github.com/user-attachments/files/16751720/MotherRussiaFlagBug.zip)

**Comment by riverwanderer** [comment]
You're observing how the module implements Fieldworks at the moment - it is via an intermediate widget. The PS counter places the widget necessarily onto open ground, where it can be rotated before dragging to a valid hex for upgrading the terrain there.

Your idea is a possible enhancement that could make the play of the counters more intuitive.

**Comment by utl94** [comment]
Ah, right. I misunderstood the current function, then. I see now the description in the CCn5.1 Reference Manual. My apologies. It was indeed my reflex to simply put the marker on the "correct" hex and then expect to pick the function after that.

**Comment by riverwanderer** [comment]
The described effects would be resolved by request #254.
