### ISSUE TITLE
No automatic discard of Counter Attack Command card in Solitaire

### ISSUE THREAD

**Issue by utl94** [riverwanderer/ccnapoleonics#259]
Module V5.1.0beta6
Vassal V3.7.14
Scenario 001 Rolica (French First Position) - 17 August 1808

Counter Attack Command card not automatically discarded in Solitaire (when countering Attack Center). This is likely true for all Counter Attack plays, some other Counter attacks were tested and found to exhibit the same behaviour. Is this intended since Counter Attack function is cleared when the Command card is discarded? If so, this is somewhat in conflict with the Reference Manual section 3.6 Guerrilla Action regarding Solitaire mode.

[CounterAttackNoAutoDiscard.zip](https://github.com/user-attachments/files/16760681/CounterAttackNoAutoDiscard.zip)

**Comment by riverwanderer** [comment]
Reproduced

**Comment by riverwanderer** [comment]
Counter-Attack inhibits normal Play action. Solitaire Discard must sit outside of this filter - moved into Card Ownership p/type and de-constructed GM&T deck's Counter Attack card to complete the fix. a804.
